name: shared_aws_api
description: Shared protocol implementation and utilities for generated AWS API clients.
version: 1.2.0

homepage: https://github.com/agilord/aws_client/tree/master/shared_aws_api

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto: ^3.0.5
  http: ^1.2.2
  meta: 1.15.0
  xml: ^6.5.0
  intl: ^0.19.0
  uuid: ^4.5.0
  collection: 1.18.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
